# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  inputs:
    # script: 'echo Write your commands here.' 
    workingDirectory: TERRAFORM/EIP/compute/aks
    # script: 'echo Write your commands here.' 
    script: |
      echo go to targted module
      terraform init
      ls

# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo go to targted module
#     cd TERRAFORM/EIP/compute/aks
#     terraform init
#     ls
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
