


trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:

  - task: CmdLine@2
    displayName: terraform paln destroy
    inputs:
      # script: 'echo Write your commands here.' 
      workingDirectory: TERRAFORM/EIP/compute/aks
      failOnStderr: true
      # azureSubscription: 
      # script: 'echo Write your commands here.' 
      script: |
        export ARM_CLIENT_ID="$[eip-terraform-dev.ARM_CLIENT_ID]"
        echo  "${{ eip-terraform-dev.ARM_CLIENT_ID }}"
        echo  "rerererererererererererererreerererererererererreer"
        export ARM_CLIENT_SECRET="Uc-8Q~AMMSmQKj5AJYaRIcKDEYwoPmRywpWjBcBr"
        export ARM_SUBSCRIPTION_ID="e9c6df82-43a6-4361-8b5c-cd513685057e"
        export ARM_TENANT_ID="2ab2b5d0-18af-4aa0-9010-cb69d0c7b92f"
        terraform init
        terraform workspace select eip.dev
        terraform plan -destroy
